export const DISPATCH_ADD_FOOD = 'DISPATCH_ADD_FOOD';
/** Writer unificato pasti: append | replace | merge (sostituisce/accorpa ADD_FOOD). */
export const DISPATCH_UPSERT_MEAL = 'DISPATCH_UPSERT_MEAL';
export const DISPATCH_ADD_WORKOUT = 'DISPATCH_ADD_WORKOUT';
export const DISPATCH_LOG_SLEEP = 'DISPATCH_LOG_SLEEP';
export const DISPATCH_LOG_STIMULANT = 'DISPATCH_LOG_STIMULANT';
export const DISPATCH_SYSTEM_MESSAGE = 'DISPATCH_SYSTEM_MESSAGE';
export const DISPATCH_COMMAND_REJECTED = 'DISPATCH_COMMAND_REJECTED';
export const DISPATCH_COMMAND_ACCEPTED = 'DISPATCH_COMMAND_ACCEPTED';

export const COMMAND_TERMINAL_EVENT_TYPES = Object.freeze({
  DISPATCH_ADD_FOOD,
  DISPATCH_UPSERT_MEAL,
  DISPATCH_ADD_WORKOUT,
  DISPATCH_LOG_SLEEP,
  DISPATCH_LOG_STIMULANT,
  DISPATCH_SYSTEM_MESSAGE,
  DISPATCH_COMMAND_REJECTED,
  DISPATCH_COMMAND_ACCEPTED,
});

export const COMMAND_TERMINAL_EVENT_TYPE_SET = new Set(
  Object.values(COMMAND_TERMINAL_EVENT_TYPES),
);

export function isKnownCommandTerminalEventType(eventType) {
  return COMMAND_TERMINAL_EVENT_TYPE_SET.has(String(eventType || ''));
}
